### ISSUE TITLE
The IO package name is case sensitive; at least when installed through pip and used on mac

### ISSUE THREAD

**Issue by VikingScientist** [SINTEF/Splipy#36]
A proposed fix would be to make it lowercase everywhere; especially in all applications in the examples folder.

**Comment by TheBB** [comment]
Really? Can you be more detailed? The IO package doesn't do any filename lookup on its own, that's delegated to the OS and the file system via Python, so I suspect if there's a bug it's somewhere else.

Happy birthday btw!

**Comment by akva2** [comment]
it's mac stupidities. even if you run with a case-insensitive fs, it still will not find IO for io.py. and pip seems to lowercase stuff on install.

**Comment by TheBB** [comment]
You're saying pip renames the folder to `io`?

**Comment by akva2** [comment]
apparently it does. not 100 that is what happens but abdullah has issues at least. whether it is pip or the filesystem is unknown however.

**Comment by VikingScientist** [comment]
The bug appears when a user on mac installs the package by `pip install splipy` followed by copy-pasting [write.py](https://github.com/sintefmath/Splipy/blob/master/examples/write.py) and runs it locally. Simply changing the IO package name to lowercase makes the application run as expected.

**Comment by VikingScientist** [comment]
> Happy birthday btw!

Yay :grinning:  Thx :tada: 

BTW: Trond is using splipy in TMA4215 so brace yourself for incoming users

**Comment by TheBB** [comment]
I can find very little about this on Google. The only thing I can find is that if the folders or files already exist, pip/mac will not change the name. I don't know if this was a 100% fresh installation of Splipy, and in fact the package **did** used to be called `io`, so that's one possibility. Being mac-deprived I can't really check even though I'm curious.

Well it *was* called `io` and it *should* be called `io`. We changed it to `IO` due to a bug I experienced, which I'm almost 100% sure was my own fault. I don't mind changing back, although I want it on record that this sounds like a [SEP™](https://www.wikiwand.com/en/Somebody_else%27s_problem).
